### ISSUE TITLE
post가 없을 때, SSG에러 발생

### ISSUE THREAD

**Issue by SanGyuk-Raccoon** [nerd-animals/na-log-engine#106]
### 기능 설명

post가 없을 때, 정상동작 확인 필요함 + UI 개선

최소조건일 때, 정상동작 확인 시, `yarn build`를 통해서 확인할 것!
- 최소조건 : public/config.json만 있을 경우
![image](https://github.com/nerd-animals/na-log-engine/assets/56672129/99de0e09-2f33-4e89-a7ff-42538c9843df)

### 참고 자료(선택)
```
Run echo $GITHUB_REPOSITORY
nerd-animals/na-log
yarn run v1.22.21
$ next build
⚠ No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

   ▲ Next.js 14.1.0

   Creating an optimized production build ...
Warning: Found 4 problems in 4 documents.

 └── Couldn't determine the document type for 4 documents. (Skipping documents)
     
     Please either define a filePathPattern for the given document type definition or provide a valid value for the type field (i.e. the field "type" needs to be one of the following document type names: Posts, Bio, About).
     
     • README.md
     • package.json
     • tsconfig.json
     • public/config.json
     

Generated 0 documents in .contentlayer
(node:2136) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 ✓ Compiled successfully
   Linting and checking validity of types ...
   Collecting page data ...

> Build error occurred
Error: Page "/post/[...slug]" is missing "generateStaticParams()" so it cannot be used with "output: export" config.
    at /home/runner/work/na-log/na-log/na-log-engine/node_modules/next/src/build/index.ts:1[8](https://github.com/nerd-animals/na-log/actions/runs/8134950152/job/22228653256#step:7:9)[9](https://github.com/nerd-animals/na-log/actions/runs/8134950152/job/22228653256#step:7:10)6:37
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Span.traceAsyncFn (/home/runner/work/na-log/na-log/na-log-engine/node_modules/next/src/trace/trace.ts:132:14)
    at async Promise.all (index 7)
    at /home/runner/work/na-log/na-log/na-log-engine/node_modules/next/src/build/index.ts:1692:9
    at Span.traceAsyncFn (/home/runner/work/na-log/na-log/na-log-engine/node_modules/next/src/trace/trace.ts:132:14)
    at /home/runner/work/na-log/na-log/na-log-engine/node_modules/next/src/build/index.ts:1585:[11](https://github.com/nerd-animals/na-log/actions/runs/8134950152/job/22228653256#step:7:12)
    at Span.traceAsyncFn (/home/runner/work/na-log/na-log/na-log-engine/node_modules/next/src/trace/trace.ts:[13](https://github.com/nerd-animals/na-log/actions/runs/8134950152/job/22228653256#step:7:14)2:[14](https://github.com/nerd-animals/na-log/actions/runs/8134950152/job/22228653256#step:7:15))
    at build (/home/runner/work/na-log/na-log/na-log-engine/node_modules/next/src/build/index.ts:7[18](https://github.com/nerd-animals/na-log/actions/runs/8134950152/job/22228653256#step:7:19):5)
    at main (/home/runner/work/na-log/na-log/na-log-engine/node_modules/next/src/bin/next.ts:1[31](https://github.com/nerd-animals/na-log/actions/runs/8134950152/job/22228653256#step:7:32):3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```
![image](https://github.com/nerd-animals/na-log-engine/assets/56672129/ed9b2c87-888a-4317-b24c-8fbbac77e181)

**Comment by SanGyuk-Raccoon** [comment]
비슷한 증상이 많은데, 빈 배열을 리턴했을 때 발생함.
 버그라고 단정짓기는 어려워보임.

'not-found' slug를 추가하는 방식으로 수정

[Link](https://github.com/vercel/next.js/issues/58171)
